export const PUT_SERVICE_LIST = 'PUT_SERVICE_LIST';
export const SET_SERVICES_LOADING_STATUS = 'SET_SERVICES_LOADING_STATUS';
export const SET_SERVICE_LOADING_STATUS = 'SET_SERVICE_LOADING_STATUS';
export const SET_SERVICE_SAVING_STATUS = 'SET_SERVICE_SAVING_STATUS';
export const UPDATE_EDIT_SERVICE_PROP = 'UPDATE_EDIT_SERVICE_PROP';
export const EDIT_SERVICE = 'EDIT_SERVICE';
